export type TProducts = {
  internalName: string,
  title: string,
  metacriticLink: string,
  dealID: string,
  storeID: string,
  gameID: string,
  salePrice: string,
  normalPrice: string,
  isOnSale: string,
  savings: string,
  metacriticScore: string,
  steamRatingText: string,
  steamRatingPercent: string,
  steamRatingCount: string,
  steamAppID: string,
  releaseDate: string,
  lastChange: string,
  dealRating: string,
  thumb: string;
}